version: "3.8"

services:

  redis:
    container_name: redis
    restart: always
    image: redis:7.2
    ports:
      - 6379:6379
    # volumes:
    #   - redis_data:/data


  web:
    container_name: backend
    build: .
    image: backend
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    command: bash -c "python src/main.py"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    restart: always

# volumes:
#   redis_data:
